// <auto-generated />
using System;
using CompanyPost.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CompanyPost.Infrastructure.Migrations
{
    [DbContext(typeof(CompanyPostDbContext))]
    [Migration("20251007114523_AddNewTableForIncomingAttachments")]
    partial class AddNewTableForIncomingAttachments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CompanyPost.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("company_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_companies");

                    b.HasIndex("CompanyCode")
                        .HasDatabaseName("ix_companies_company_code");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.ContractAttachments", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("ContractID")
                        .HasColumnType("char(36)")
                        .HasColumnName("contract_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.HasKey("Id")
                        .HasName("pk_contract_attachments");

                    b.HasIndex("ContractID")
                        .HasDatabaseName("ix_contract_attachments_contract_id");

                    b.ToTable("contract_attachments", (string)null);
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.Contracts", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("ContractNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("contract_number");

                    b.Property<DateTime>("Contract_Date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("contract_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by_id");

                    b.Property<int>("Currency")
                        .HasColumnType("int")
                        .HasColumnName("currency");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("details");

                    b.Property<string>("Notes")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("notes");

                    b.Property<Guid>("PersonOrgId")
                        .HasColumnType("char(36)")
                        .HasColumnName("person_org_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)")
                        .HasColumnName("project_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("value");

                    b.Property<string>("purchase_order_ref")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("purchase_order_ref");

                    b.Property<string>("working")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("working");

                    b.HasKey("Id")
                        .HasName("pk_contracts");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_contracts_created_by_id");

                    b.HasIndex("PersonOrgId")
                        .HasDatabaseName("ix_contracts_person_org_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_contracts_project_id");

                    b.ToTable("contracts", (string)null);
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.InComing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("delivery_date");

                    b.Property<int>("DeliveryMethods")
                        .HasColumnType("int")
                        .HasColumnName("delivery_methods");

                    b.Property<DateTime>("DocumentDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("document_date");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("document_number");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int")
                        .HasColumnName("document_type");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext")
                        .HasColumnName("notes");

                    b.Property<Guid>("OriginalPublisherId")
                        .HasColumnType("char(36)")
                        .HasColumnName("original_publisher_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)")
                        .HasColumnName("project_id");

                    b.Property<Guid>("PublishedId")
                        .HasColumnType("char(36)")
                        .HasColumnName("published_id");

                    b.Property<DateTime>("SaveDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("save_date");

                    b.Property<int>("SerialNumber")
                        .HasColumnType("int")
                        .HasColumnName("serial_number");

                    b.Property<string>("Subject")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("subject");

                    b.Property<string>("Summary")
                        .HasColumnType("longtext")
                        .HasColumnName("summary");

                    b.HasKey("Id")
                        .HasName("pk_in_coming");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_in_coming_created_by_id");

                    b.HasIndex("OriginalPublisherId")
                        .HasDatabaseName("ix_in_coming_original_publisher_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_in_coming_project_id");

                    b.HasIndex("PublishedId")
                        .HasDatabaseName("ix_in_coming_published_id");

                    b.ToTable("in_coming", (string)null);
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.IncomingAttachments", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("file_name");

                    b.Property<Guid>("IncomingId")
                        .HasColumnType("char(36)")
                        .HasColumnName("incoming_id");

                    b.HasKey("Id")
                        .HasName("pk_incoming_attachments");

                    b.HasIndex("IncomingId")
                        .HasDatabaseName("ix_incoming_attachments_incoming_id");

                    b.ToTable("incoming_attachments", (string)null);
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.PersonOrg", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("address");

                    b.Property<string>("Contact_Person")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("contact_person");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("SAP_BP")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("sap_bp");

                    b.HasKey("Id")
                        .HasName("pk_person_orgs");

                    b.ToTable("person_orgs", (string)null);
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.PostExternal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("AboutWork")
                        .HasColumnType("longtext")
                        .HasColumnName("about_work");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("delivery_date");

                    b.Property<int>("DeliveryMethods")
                        .HasColumnType("int")
                        .HasColumnName("delivery_methods");

                    b.Property<DateTime>("DocumentDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("document_date");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("document_number");

                    b.Property<string>("IncomingNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("incoming_number");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext")
                        .HasColumnName("notes");

                    b.Property<Guid>("PublishedId")
                        .HasColumnType("char(36)")
                        .HasColumnName("published_id");

                    b.Property<Guid>("RecievedFromId")
                        .HasColumnType("char(36)")
                        .HasColumnName("recieved_from_id");

                    b.Property<int>("SerialNumber")
                        .HasColumnType("int")
                        .HasColumnName("serial_number");

                    b.Property<string>("Subject")
                        .HasColumnType("longtext")
                        .HasColumnName("subject");

                    b.Property<string>("Summary")
                        .HasColumnType("longtext")
                        .HasColumnName("summary");

                    b.HasKey("Id")
                        .HasName("pk_post_externals");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_post_externals_company_id");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_post_externals_created_by_id");

                    b.HasIndex("PublishedId")
                        .HasDatabaseName("ix_post_externals_published_id");

                    b.HasIndex("RecievedFromId")
                        .HasDatabaseName("ix_post_externals_recieved_from_id");

                    b.ToTable("post_externals", (string)null);
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.PostExternalAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("file_name");

                    b.Property<Guid>("PostExternalId")
                        .HasColumnType("char(36)")
                        .HasColumnName("post_external_id");

                    b.HasKey("Id")
                        .HasName("pk_post_external_attachments");

                    b.HasIndex("PostExternalId")
                        .HasDatabaseName("ix_post_external_attachments_post_external_id");

                    b.ToTable("post_external_attachments", (string)null);
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.PostInternal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("AboutWork")
                        .HasColumnType("longtext")
                        .HasColumnName("about_work");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("delivery_date");

                    b.Property<int>("DeliveryMethods")
                        .HasColumnType("int")
                        .HasColumnName("delivery_methods");

                    b.Property<DateTime>("DocumentDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("document_date");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("document_number");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext")
                        .HasColumnName("notes");

                    b.Property<Guid>("PublishedId")
                        .HasColumnType("char(36)")
                        .HasColumnName("published_id");

                    b.Property<Guid>("RecievedFromId")
                        .HasColumnType("char(36)")
                        .HasColumnName("recieved_from_id");

                    b.Property<int>("SerialNumber")
                        .HasColumnType("int")
                        .HasColumnName("serial_number");

                    b.Property<string>("Subject")
                        .HasColumnType("longtext")
                        .HasColumnName("subject");

                    b.Property<string>("Summary")
                        .HasColumnType("longtext")
                        .HasColumnName("summary");

                    b.HasKey("Id")
                        .HasName("pk_post_internals");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_post_internals_company_id");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_post_internals_created_by_id");

                    b.HasIndex("PublishedId")
                        .HasDatabaseName("ix_post_internals_published_id");

                    b.HasIndex("RecievedFromId")
                        .HasDatabaseName("ix_post_internals_recieved_from_id");

                    b.ToTable("post_internals", (string)null);
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.PostInternalAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("file_name");

                    b.Property<Guid>("PostInternalId")
                        .HasColumnType("char(36)")
                        .HasColumnName("post_internal_id");

                    b.HasKey("Id")
                        .HasName("pk_post_internal_attachments");

                    b.HasIndex("PostInternalId")
                        .HasDatabaseName("ix_post_internal_attachments_post_internal_id");

                    b.ToTable("post_internal_attachments", (string)null);
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.PostTransformer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("AboutWork")
                        .HasColumnType("longtext")
                        .HasColumnName("about_work");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("delivery_date");

                    b.Property<int>("DeliveryMethods")
                        .HasColumnType("int")
                        .HasColumnName("delivery_methods");

                    b.Property<DateTime>("DocumentDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("document_date");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("document_number");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int")
                        .HasColumnName("document_type");

                    b.Property<string>("FollowingPerson")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("following_person");

                    b.Property<string>("IncomingNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("incoming_number");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext")
                        .HasColumnName("notes");

                    b.Property<string>("PostNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("post_number");

                    b.Property<Guid>("PublishedId")
                        .HasColumnType("char(36)")
                        .HasColumnName("published_id");

                    b.Property<Guid>("RecievedFromId")
                        .HasColumnType("char(36)")
                        .HasColumnName("recieved_from_id");

                    b.Property<string>("RecivedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("recived_by_name");

                    b.Property<int>("SerialNumber")
                        .HasColumnType("int")
                        .HasColumnName("serial_number");

                    b.Property<string>("Subject")
                        .HasColumnType("longtext")
                        .HasColumnName("subject");

                    b.Property<string>("Summary")
                        .HasColumnType("longtext")
                        .HasColumnName("summary");

                    b.HasKey("Id")
                        .HasName("pk_post_transformers");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_post_transformers_company_id");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_post_transformers_created_by_id");

                    b.HasIndex("PublishedId")
                        .HasDatabaseName("ix_post_transformers_published_id");

                    b.HasIndex("RecievedFromId")
                        .HasDatabaseName("ix_post_transformers_recieved_from_id");

                    b.ToTable("post_transformers", (string)null);
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.PostTransformerAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("file_name");

                    b.Property<Guid>("PostTransformerId")
                        .HasColumnType("char(36)")
                        .HasColumnName("post_transformer_id");

                    b.HasKey("Id")
                        .HasName("pk_post_transformer_attachments");

                    b.HasIndex("PostTransformerId")
                        .HasDatabaseName("ix_post_transformer_attachments_post_transformer_id");

                    b.ToTable("post_transformer_attachments", (string)null);
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.Projects", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.Publisher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDepartment")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_department");

                    b.Property<bool>("IsProject")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_project");

                    b.Property<bool>("IsSupplierOrSubContractor")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_supplier_or_sub_contractor");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_publishers");

                    b.ToTable("publishers", (string)null);
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.SysUsers", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_sys_users");

                    b.ToTable("sys_users", (string)null);
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.ContractAttachments", b =>
                {
                    b.HasOne("CompanyPost.Domain.Entities.Contracts", "Contracts")
                        .WithMany("ContractAttachments")
                        .HasForeignKey("ContractID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contract_attachments_contracts_contract_id");

                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.Contracts", b =>
                {
                    b.HasOne("CompanyPost.Domain.Entities.SysUsers", "CreatedBy")
                        .WithMany("Contracts")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contracts_sys_users_created_by_id");

                    b.HasOne("CompanyPost.Domain.Entities.PersonOrg", "PersonOrgs")
                        .WithMany("Contracts")
                        .HasForeignKey("PersonOrgId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contracts_person_orgs_person_org_id");

                    b.HasOne("CompanyPost.Domain.Entities.Projects", "Projects")
                        .WithMany("Contracts")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contracts_projects_project_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("PersonOrgs");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.InComing", b =>
                {
                    b.HasOne("CompanyPost.Domain.Entities.SysUsers", "CreatedBy")
                        .WithMany("IncomingDocuments")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_in_coming_sys_users_created_by_id");

                    b.HasOne("CompanyPost.Domain.Entities.Publisher", "OriginalPublisher")
                        .WithMany("OriginalPublisherInComings")
                        .HasForeignKey("OriginalPublisherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_in_coming_publishers_original_publisher_id");

                    b.HasOne("CompanyPost.Domain.Entities.Projects", "Projects")
                        .WithMany("InComings")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_in_coming_projects_project_id");

                    b.HasOne("CompanyPost.Domain.Entities.Publisher", "Publisher")
                        .WithMany("PublishedInComings")
                        .HasForeignKey("PublishedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_in_coming_publishers_published_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("OriginalPublisher");

                    b.Navigation("Projects");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.IncomingAttachments", b =>
                {
                    b.HasOne("CompanyPost.Domain.Entities.InComing", "Incoming")
                        .WithMany("IncomingAttachments")
                        .HasForeignKey("IncomingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_incoming_attachments_in_coming_incoming_id");

                    b.Navigation("Incoming");
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.PostExternal", b =>
                {
                    b.HasOne("CompanyPost.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_externals_companies_company_id");

                    b.HasOne("CompanyPost.Domain.Entities.SysUsers", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_externals_sys_users_created_by_id");

                    b.HasOne("CompanyPost.Domain.Entities.Publisher", "Publisher")
                        .WithMany("PublishedPostExternals")
                        .HasForeignKey("PublishedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_post_externals_publishers_published_id");

                    b.HasOne("CompanyPost.Domain.Entities.Publisher", "RecievedFrom")
                        .WithMany("RecievedPostExternals")
                        .HasForeignKey("RecievedFromId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_post_externals_publishers_recieved_from_id");

                    b.Navigation("Company");

                    b.Navigation("CreatedBy");

                    b.Navigation("Publisher");

                    b.Navigation("RecievedFrom");
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.PostExternalAttachment", b =>
                {
                    b.HasOne("CompanyPost.Domain.Entities.PostExternal", "PostExternal")
                        .WithMany("Attachments")
                        .HasForeignKey("PostExternalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_post_external_attachments_post_externals_post_external_id");

                    b.Navigation("PostExternal");
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.PostInternal", b =>
                {
                    b.HasOne("CompanyPost.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_internals_companies_company_id");

                    b.HasOne("CompanyPost.Domain.Entities.SysUsers", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_internals_sys_users_created_by_id");

                    b.HasOne("CompanyPost.Domain.Entities.Publisher", "Publisher")
                        .WithMany("PublishedPostInternals")
                        .HasForeignKey("PublishedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_post_internals_publishers_published_id");

                    b.HasOne("CompanyPost.Domain.Entities.Publisher", "RecievedFrom")
                        .WithMany("RecievedPostInternals")
                        .HasForeignKey("RecievedFromId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_post_internals_publishers_recieved_from_id");

                    b.Navigation("Company");

                    b.Navigation("CreatedBy");

                    b.Navigation("Publisher");

                    b.Navigation("RecievedFrom");
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.PostInternalAttachment", b =>
                {
                    b.HasOne("CompanyPost.Domain.Entities.PostInternal", "PostInternal")
                        .WithMany("Attachments")
                        .HasForeignKey("PostInternalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_post_internal_attachments_post_internals_post_internal_id");

                    b.Navigation("PostInternal");
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.PostTransformer", b =>
                {
                    b.HasOne("CompanyPost.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_transformers_companies_company_id");

                    b.HasOne("CompanyPost.Domain.Entities.SysUsers", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_transformers_sys_users_created_by_id");

                    b.HasOne("CompanyPost.Domain.Entities.Publisher", "Publisher")
                        .WithMany("PublishedPostTransformers")
                        .HasForeignKey("PublishedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_post_transformers_publishers_published_id");

                    b.HasOne("CompanyPost.Domain.Entities.Publisher", "RecievedFrom")
                        .WithMany("RecievedPostTransformers")
                        .HasForeignKey("RecievedFromId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_post_transformers_publishers_recieved_from_id");

                    b.Navigation("Company");

                    b.Navigation("CreatedBy");

                    b.Navigation("Publisher");

                    b.Navigation("RecievedFrom");
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.PostTransformerAttachment", b =>
                {
                    b.HasOne("CompanyPost.Domain.Entities.PostTransformer", "PostTransformer")
                        .WithMany("Attachments")
                        .HasForeignKey("PostTransformerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_post_transformer_attachments_post_transformers_post_transfor");

                    b.Navigation("PostTransformer");
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.Contracts", b =>
                {
                    b.Navigation("ContractAttachments");
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.InComing", b =>
                {
                    b.Navigation("IncomingAttachments");
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.PersonOrg", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.PostExternal", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.PostInternal", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.PostTransformer", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.Projects", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("InComings");
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.Publisher", b =>
                {
                    b.Navigation("OriginalPublisherInComings");

                    b.Navigation("PublishedInComings");

                    b.Navigation("PublishedPostExternals");

                    b.Navigation("PublishedPostInternals");

                    b.Navigation("PublishedPostTransformers");

                    b.Navigation("RecievedPostExternals");

                    b.Navigation("RecievedPostInternals");

                    b.Navigation("RecievedPostTransformers");
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.SysUsers", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("IncomingDocuments");
                });
#pragma warning restore 612, 618
        }
    }
}
