// <auto-generated />
using System;
using CompanyPost.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CompanyPost.Infrastructure.Migrations
{
    [DbContext(typeof(CompanyPostDbContext))]
    [Migration("20251109232746_AddConstraintForContractAttachmentWithRefAndContractWhenDeletingCascade")]
    partial class AddConstraintForContractAttachmentWithRefAndContractWhenDeletingCascade
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CompanyPost.Domain.Entities.BridgeUsers", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_bridge_users");

                    b.ToTable("bridge_users", (string)null);
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("company_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_companies");

                    b.HasIndex("CompanyCode")
                        .HasDatabaseName("ix_companies_company_code");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.ContractAttachments", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid?>("ContractID")
                        .HasColumnType("char(36)")
                        .HasColumnName("contract_id");

                    b.Property<Guid?>("ContractRefId")
                        .HasColumnType("char(36)")
                        .HasColumnName("contract_ref_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("file_name");

                    b.HasKey("Id")
                        .HasName("pk_contract_attachments");

                    b.HasIndex("ContractID")
                        .HasDatabaseName("ix_contract_attachments_contract_id");

                    b.HasIndex("ContractRefId")
                        .HasDatabaseName("ix_contract_attachments_contract_ref_id");

                    b.ToTable("contract_attachments", (string)null);
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.ContractRef", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("char(36)")
                        .HasColumnName("contract_id");

                    b.Property<string>("ContractNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("contract_number");

                    b.Property<string>("ContractNumberRef")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("contract_number_ref");

                    b.Property<DateTime>("Contract_Date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("contract_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by_id");

                    b.Property<int>("Currency")
                        .HasColumnType("int")
                        .HasColumnName("currency");

                    b.Property<int>("Department")
                        .HasColumnType("int")
                        .HasColumnName("department");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("details");

                    b.Property<string>("Notes")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("notes");

                    b.Property<Guid>("PersonOrgId")
                        .HasColumnType("char(36)")
                        .HasColumnName("person_org_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)")
                        .HasColumnName("project_id");

                    b.Property<int>("SerialNumber")
                        .HasColumnType("int")
                        .HasColumnName("serial_number");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("value");

                    b.Property<Guid>("WorkTypeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("work_type_id");

                    b.Property<string>("purchase_order_ref")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("purchase_order_ref");

                    b.HasKey("Id")
                        .HasName("pk_contract_refs");

                    b.HasIndex("ContractId")
                        .HasDatabaseName("ix_contract_refs_contract_id");

                    b.HasIndex("ContractNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_contract_refs_contract_number");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_contract_refs_created_by_id");

                    b.HasIndex("PersonOrgId")
                        .HasDatabaseName("ix_contract_refs_person_org_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_contract_refs_project_id");

                    b.HasIndex("WorkTypeId")
                        .HasDatabaseName("ix_contract_refs_work_type_id");

                    b.HasIndex("purchase_order_ref")
                        .IsUnique()
                        .HasDatabaseName("ix_contract_refs_purchase_order_ref");

                    b.ToTable("contract_refs", (string)null);
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.Contracts", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("ContractNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("contract_number");

                    b.Property<DateTime>("Contract_Date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("contract_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by_id");

                    b.Property<int>("Currency")
                        .HasColumnType("int")
                        .HasColumnName("currency");

                    b.Property<int>("Department")
                        .HasColumnType("int")
                        .HasColumnName("department");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("details");

                    b.Property<bool>("HasReference")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("has_reference");

                    b.Property<string>("Notes")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("notes");

                    b.Property<Guid>("PersonOrgId")
                        .HasColumnType("char(36)")
                        .HasColumnName("person_org_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)")
                        .HasColumnName("project_id");

                    b.Property<int>("SerialNumber")
                        .HasColumnType("int")
                        .HasColumnName("serial_number");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("value");

                    b.Property<Guid>("WorkTypeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("work_type_id");

                    b.Property<string>("purchase_order_ref")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("purchase_order_ref");

                    b.HasKey("Id")
                        .HasName("pk_contracts");

                    b.HasIndex("ContractNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_contracts_contract_number");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_contracts_created_by_id");

                    b.HasIndex("PersonOrgId")
                        .HasDatabaseName("ix_contracts_person_org_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_contracts_project_id");

                    b.HasIndex("WorkTypeId")
                        .HasDatabaseName("ix_contracts_work_type_id");

                    b.HasIndex("purchase_order_ref")
                        .IsUnique()
                        .HasDatabaseName("ix_contracts_purchase_order_ref");

                    b.ToTable("contracts", (string)null);
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.Employees", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_employees");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.InComing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("delivery_date");

                    b.Property<int>("DeliveryMethods")
                        .HasColumnType("int")
                        .HasColumnName("delivery_methods");

                    b.Property<int>("Department")
                        .HasColumnType("int")
                        .HasColumnName("department");

                    b.Property<DateTime>("DocumentDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("document_date");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("document_number");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int")
                        .HasColumnName("document_type");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext")
                        .HasColumnName("notes");

                    b.Property<Guid>("OriginalPublisherId")
                        .HasColumnType("char(36)")
                        .HasColumnName("original_publisher_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)")
                        .HasColumnName("project_id");

                    b.Property<Guid>("PublishedId")
                        .HasColumnType("char(36)")
                        .HasColumnName("published_id");

                    b.Property<DateTime>("SaveDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("save_date");

                    b.Property<int>("SerialNumber")
                        .HasColumnType("int")
                        .HasColumnName("serial_number");

                    b.Property<string>("Subject")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("subject");

                    b.Property<string>("Summary")
                        .HasColumnType("longtext")
                        .HasColumnName("summary");

                    b.Property<Guid>("WorkTypeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("work_type_id");

                    b.HasKey("Id")
                        .HasName("pk_in_coming");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_in_coming_created_by_id");

                    b.HasIndex("DocumentNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_in_coming_document_number");

                    b.HasIndex("OriginalPublisherId")
                        .HasDatabaseName("ix_in_coming_original_publisher_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_in_coming_project_id");

                    b.HasIndex("PublishedId")
                        .HasDatabaseName("ix_in_coming_published_id");

                    b.HasIndex("WorkTypeId")
                        .HasDatabaseName("ix_in_coming_work_type_id");

                    b.ToTable("in_coming", (string)null);
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.InComingAttachments", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("file_name");

                    b.Property<Guid>("IncomingId")
                        .HasColumnType("char(36)")
                        .HasColumnName("incoming_id");

                    b.HasKey("Id")
                        .HasName("pk_in_coming_attachments");

                    b.HasIndex("IncomingId")
                        .HasDatabaseName("ix_in_coming_attachments_incoming_id");

                    b.ToTable("in_coming_attachments", (string)null);
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.InComingResponsibleEmployee", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("employee_id");

                    b.Property<Guid>("InComingId")
                        .HasColumnType("char(36)")
                        .HasColumnName("in_coming_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.HasKey("EmployeeId", "InComingId", "Id")
                        .HasName("pk_in_coming_responsible_employees");

                    b.HasIndex("InComingId")
                        .HasDatabaseName("ix_in_coming_responsible_employees_in_coming_id");

                    b.ToTable("in_coming_responsible_employees", (string)null);
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.PostExternal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("AboutWork")
                        .HasColumnType("longtext")
                        .HasColumnName("about_work");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("delivery_date");

                    b.Property<int>("DeliveryMethods")
                        .HasColumnType("int")
                        .HasColumnName("delivery_methods");

                    b.Property<int>("Department")
                        .HasColumnType("int")
                        .HasColumnName("department");

                    b.Property<DateTime>("DocumentDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("document_date");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("document_number");

                    b.Property<string>("IncomingNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("incoming_number");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext")
                        .HasColumnName("notes");

                    b.Property<Guid>("PublishedId")
                        .HasColumnType("char(36)")
                        .HasColumnName("published_id");

                    b.Property<Guid>("ReceivedFromSupplierId")
                        .HasColumnType("char(36)")
                        .HasColumnName("received_from_supplier_id");

                    b.Property<int>("SerialNumber")
                        .HasColumnType("int")
                        .HasColumnName("serial_number");

                    b.Property<string>("Subject")
                        .HasColumnType("longtext")
                        .HasColumnName("subject");

                    b.Property<string>("Summary")
                        .HasColumnType("longtext")
                        .HasColumnName("summary");

                    b.Property<Guid>("WorkTypeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("work_type_id");

                    b.HasKey("Id")
                        .HasName("pk_post_externals");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_post_externals_company_id");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_post_externals_created_by_id");

                    b.HasIndex("DocumentNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_post_externals_document_number");

                    b.HasIndex("PublishedId")
                        .HasDatabaseName("ix_post_externals_published_id");

                    b.HasIndex("ReceivedFromSupplierId")
                        .HasDatabaseName("ix_post_externals_received_from_supplier_id");

                    b.HasIndex("WorkTypeId")
                        .HasDatabaseName("ix_post_externals_work_type_id");

                    b.ToTable("post_externals", (string)null);
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.PostExternalAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("file_name");

                    b.Property<Guid>("PostExternalId")
                        .HasColumnType("char(36)")
                        .HasColumnName("post_external_id");

                    b.HasKey("Id")
                        .HasName("pk_post_external_attachments");

                    b.HasIndex("PostExternalId")
                        .HasDatabaseName("ix_post_external_attachments_post_external_id");

                    b.ToTable("post_external_attachments", (string)null);
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.PostInternal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("AboutWork")
                        .HasColumnType("longtext")
                        .HasColumnName("about_work");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("delivery_date");

                    b.Property<int>("DeliveryMethods")
                        .HasColumnType("int")
                        .HasColumnName("delivery_methods");

                    b.Property<int>("Department")
                        .HasColumnType("int")
                        .HasColumnName("department");

                    b.Property<DateTime>("DocumentDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("document_date");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("document_number");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext")
                        .HasColumnName("notes");

                    b.Property<Guid>("PublishedId")
                        .HasColumnType("char(36)")
                        .HasColumnName("published_id");

                    b.Property<Guid>("RecievedFromId")
                        .HasColumnType("char(36)")
                        .HasColumnName("recieved_from_id");

                    b.Property<int>("SerialNumber")
                        .HasColumnType("int")
                        .HasColumnName("serial_number");

                    b.Property<string>("Subject")
                        .HasColumnType("longtext")
                        .HasColumnName("subject");

                    b.Property<string>("Summary")
                        .HasColumnType("longtext")
                        .HasColumnName("summary");

                    b.Property<Guid>("WorkTypeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("work_type_id");

                    b.HasKey("Id")
                        .HasName("pk_post_internals");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_post_internals_company_id");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_post_internals_created_by_id");

                    b.HasIndex("DocumentNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_post_internals_document_number");

                    b.HasIndex("PublishedId")
                        .HasDatabaseName("ix_post_internals_published_id");

                    b.HasIndex("RecievedFromId")
                        .HasDatabaseName("ix_post_internals_recieved_from_id");

                    b.HasIndex("WorkTypeId")
                        .HasDatabaseName("ix_post_internals_work_type_id");

                    b.ToTable("post_internals", (string)null);
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.PostInternalAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("file_name");

                    b.Property<Guid>("PostInternalId")
                        .HasColumnType("char(36)")
                        .HasColumnName("post_internal_id");

                    b.HasKey("Id")
                        .HasName("pk_post_internal_attachments");

                    b.HasIndex("PostInternalId")
                        .HasDatabaseName("ix_post_internal_attachments_post_internal_id");

                    b.ToTable("post_internal_attachments", (string)null);
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.PostTransformer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("AboutWork")
                        .HasColumnType("longtext")
                        .HasColumnName("about_work");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("delivery_date");

                    b.Property<int>("DeliveryMethods")
                        .HasColumnType("int")
                        .HasColumnName("delivery_methods");

                    b.Property<int>("Department")
                        .HasColumnType("int")
                        .HasColumnName("department");

                    b.Property<DateTime>("DocumentDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("document_date");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("document_number");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int")
                        .HasColumnName("document_type");

                    b.Property<string>("FollowingPerson")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("following_person");

                    b.Property<string>("IncomingNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("incoming_number");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext")
                        .HasColumnName("notes");

                    b.Property<string>("PostNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("post_number");

                    b.Property<Guid>("PublishedId")
                        .HasColumnType("char(36)")
                        .HasColumnName("published_id");

                    b.Property<Guid>("RecievedFromId")
                        .HasColumnType("char(36)")
                        .HasColumnName("recieved_from_id");

                    b.Property<string>("RecivedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("recived_by_name");

                    b.Property<int>("SerialNumber")
                        .HasColumnType("int")
                        .HasColumnName("serial_number");

                    b.Property<string>("Subject")
                        .HasColumnType("longtext")
                        .HasColumnName("subject");

                    b.Property<string>("Summary")
                        .HasColumnType("longtext")
                        .HasColumnName("summary");

                    b.Property<Guid>("WorkTypeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("work_type_id");

                    b.HasKey("Id")
                        .HasName("pk_post_transformers");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_post_transformers_company_id");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_post_transformers_created_by_id");

                    b.HasIndex("DocumentNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_post_transformers_document_number");

                    b.HasIndex("PublishedId")
                        .HasDatabaseName("ix_post_transformers_published_id");

                    b.HasIndex("RecievedFromId")
                        .HasDatabaseName("ix_post_transformers_recieved_from_id");

                    b.HasIndex("WorkTypeId")
                        .HasDatabaseName("ix_post_transformers_work_type_id");

                    b.ToTable("post_transformers", (string)null);
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.PostTransformerAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("file_name");

                    b.Property<Guid>("PostTransformerId")
                        .HasColumnType("char(36)")
                        .HasColumnName("post_transformer_id");

                    b.HasKey("Id")
                        .HasName("pk_post_transformer_attachments");

                    b.HasIndex("PostTransformerId")
                        .HasDatabaseName("ix_post_transformer_attachments_post_transformer_id");

                    b.ToTable("post_transformer_attachments", (string)null);
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.Publisher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDepartment")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_department");

                    b.Property<bool>("IsProject")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_project");

                    b.Property<bool>("IsSupplierOrSubContractor")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_supplier_or_sub_contractor");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_publishers");

                    b.ToTable("publishers", (string)null);
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.PurchaseOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by_id");

                    b.Property<int>("Currency")
                        .HasColumnType("int")
                        .HasColumnName("currency");

                    b.Property<int>("Department")
                        .HasColumnType("int")
                        .HasColumnName("department");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("details");

                    b.Property<string>("Notes")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("notes");

                    b.Property<Guid>("PersonOrgId")
                        .HasColumnType("char(36)")
                        .HasColumnName("person_org_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)")
                        .HasColumnName("project_id");

                    b.Property<string>("PurchaseOrderNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("purchase_order_number");

                    b.Property<int>("PurchaseOrderTypes")
                        .HasColumnType("int")
                        .HasColumnName("purchase_order_types");

                    b.Property<DateTime>("PurchaseOrder_Date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("purchase_order_date");

                    b.Property<int>("SerialNumber")
                        .HasColumnType("int")
                        .HasColumnName("serial_number");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("value");

                    b.Property<Guid>("WorkTypeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("work_type_id");

                    b.HasKey("Id")
                        .HasName("pk_purchase_orders");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_purchase_orders_created_by_id");

                    b.HasIndex("PersonOrgId")
                        .HasDatabaseName("ix_purchase_orders_person_org_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_purchase_orders_project_id");

                    b.HasIndex("PurchaseOrderNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_purchase_orders_purchase_order_number");

                    b.HasIndex("WorkTypeId")
                        .HasDatabaseName("ix_purchase_orders_work_type_id");

                    b.ToTable("purchase_orders", (string)null);
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.PurchaseOrderAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("file_name");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("char(36)")
                        .HasColumnName("purchase_order_id");

                    b.HasKey("Id")
                        .HasName("pk_purchase_order_attachments");

                    b.HasIndex("PurchaseOrderId")
                        .HasDatabaseName("ix_purchase_order_attachments_purchase_order_id");

                    b.ToTable("purchase_order_attachments", (string)null);
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.SysUsers", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("HrCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("hr_code");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_admin");

                    b.Property<bool>("IsPasswordDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_password_default")
                        .HasDefaultValueSql("1");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_verified");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_sys_users");

                    b.ToTable("sys_users", (string)null);
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.SysUsersCompany", b =>
                {
                    b.Property<Guid>("SysUserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("sys_user_id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("company_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.HasKey("SysUserId", "CompanyId", "Id")
                        .HasName("pk_sys_users_companies");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_sys_users_companies_company_id");

                    b.ToTable("sys_users_companies", (string)null);
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.WorkType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_work_types");

                    b.ToTable("work_types", (string)null);
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.ContractAttachments", b =>
                {
                    b.HasOne("CompanyPost.Domain.Entities.Contracts", "Contracts")
                        .WithMany("ContractAttachments")
                        .HasForeignKey("ContractID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_contract_attachments_contracts_contract_id");

                    b.HasOne("CompanyPost.Domain.Entities.ContractRef", "ContractRef")
                        .WithMany("ContractAttachments")
                        .HasForeignKey("ContractRefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_contract_attachments_contract_refs_contract_ref_id");

                    b.Navigation("ContractRef");

                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.ContractRef", b =>
                {
                    b.HasOne("CompanyPost.Domain.Entities.Contracts", "Contract")
                        .WithMany("ContractRefs")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contract_refs_contracts_contract_id");

                    b.HasOne("CompanyPost.Domain.Entities.SysUsers", "CreatedBy")
                        .WithMany("ContractRefs")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contract_refs_sys_users_created_by_id");

                    b.HasOne("CompanyPost.Domain.Entities.Publisher", "PersonOrgs")
                        .WithMany("ContractRefPersonOrgs")
                        .HasForeignKey("PersonOrgId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contract_refs_publishers_person_org_id");

                    b.HasOne("CompanyPost.Domain.Entities.Publisher", "Projects")
                        .WithMany("ContractRefProjects")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contract_refs_publishers_project_id");

                    b.HasOne("CompanyPost.Domain.Entities.WorkType", "WorkType")
                        .WithMany("ContractRefs")
                        .HasForeignKey("WorkTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contract_refs_work_types_work_type_id");

                    b.Navigation("Contract");

                    b.Navigation("CreatedBy");

                    b.Navigation("PersonOrgs");

                    b.Navigation("Projects");

                    b.Navigation("WorkType");
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.Contracts", b =>
                {
                    b.HasOne("CompanyPost.Domain.Entities.SysUsers", "CreatedBy")
                        .WithMany("Contracts")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contracts_sys_users_created_by_id");

                    b.HasOne("CompanyPost.Domain.Entities.Publisher", "PersonOrgs")
                        .WithMany("ContractsPersonOrgs")
                        .HasForeignKey("PersonOrgId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contracts_publishers_person_org_id");

                    b.HasOne("CompanyPost.Domain.Entities.Publisher", "Projects")
                        .WithMany("ContractsProjects")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contracts_publishers_project_id");

                    b.HasOne("CompanyPost.Domain.Entities.WorkType", "WorkType")
                        .WithMany("Contracts")
                        .HasForeignKey("WorkTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contracts_work_types_work_type_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("PersonOrgs");

                    b.Navigation("Projects");

                    b.Navigation("WorkType");
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.InComing", b =>
                {
                    b.HasOne("CompanyPost.Domain.Entities.SysUsers", "CreatedBy")
                        .WithMany("IncomingDocuments")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_in_coming_sys_users_created_by_id");

                    b.HasOne("CompanyPost.Domain.Entities.Publisher", "OriginalPublisher")
                        .WithMany("OriginalPublisherInComings")
                        .HasForeignKey("OriginalPublisherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_in_coming_publishers_original_publisher_id");

                    b.HasOne("CompanyPost.Domain.Entities.Publisher", "Projects")
                        .WithMany("IncomingProjects")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_in_coming_publishers_project_id");

                    b.HasOne("CompanyPost.Domain.Entities.Publisher", "Publisher")
                        .WithMany("PublishedInComings")
                        .HasForeignKey("PublishedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_in_coming_publishers_published_id");

                    b.HasOne("CompanyPost.Domain.Entities.WorkType", "WorkType")
                        .WithMany("InComings")
                        .HasForeignKey("WorkTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_in_coming_work_types_work_type_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("OriginalPublisher");

                    b.Navigation("Projects");

                    b.Navigation("Publisher");

                    b.Navigation("WorkType");
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.InComingAttachments", b =>
                {
                    b.HasOne("CompanyPost.Domain.Entities.InComing", "Incoming")
                        .WithMany("IncomingAttachments")
                        .HasForeignKey("IncomingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_in_coming_attachments_in_coming_incoming_id");

                    b.Navigation("Incoming");
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.InComingResponsibleEmployee", b =>
                {
                    b.HasOne("CompanyPost.Domain.Entities.Employees", "Employees")
                        .WithMany("inComingResponsibleEmployees")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_in_coming_responsible_employees_employees_employee_id");

                    b.HasOne("CompanyPost.Domain.Entities.InComing", "InComing")
                        .WithMany("inComingResponsibleEmployees")
                        .HasForeignKey("InComingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_in_coming_responsible_employees_in_coming_in_coming_id");

                    b.Navigation("Employees");

                    b.Navigation("InComing");
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.PostExternal", b =>
                {
                    b.HasOne("CompanyPost.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_externals_companies_company_id");

                    b.HasOne("CompanyPost.Domain.Entities.SysUsers", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_externals_sys_users_created_by_id");

                    b.HasOne("CompanyPost.Domain.Entities.Publisher", "Publisher")
                        .WithMany("PublishedPostExternals")
                        .HasForeignKey("PublishedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_post_externals_publishers_published_id");

                    b.HasOne("CompanyPost.Domain.Entities.Publisher", "ReceivedFromSupplier")
                        .WithMany("RecievedPostExternals")
                        .HasForeignKey("ReceivedFromSupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_post_externals_publishers_received_from_supplier_id");

                    b.HasOne("CompanyPost.Domain.Entities.WorkType", "WorkType")
                        .WithMany("PostExternals")
                        .HasForeignKey("WorkTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_post_externals_work_types_work_type_id");

                    b.Navigation("Company");

                    b.Navigation("CreatedBy");

                    b.Navigation("Publisher");

                    b.Navigation("ReceivedFromSupplier");

                    b.Navigation("WorkType");
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.PostExternalAttachment", b =>
                {
                    b.HasOne("CompanyPost.Domain.Entities.PostExternal", "PostExternal")
                        .WithMany("Attachments")
                        .HasForeignKey("PostExternalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_post_external_attachments_post_externals_post_external_id");

                    b.Navigation("PostExternal");
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.PostInternal", b =>
                {
                    b.HasOne("CompanyPost.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_internals_companies_company_id");

                    b.HasOne("CompanyPost.Domain.Entities.SysUsers", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_internals_sys_users_created_by_id");

                    b.HasOne("CompanyPost.Domain.Entities.Publisher", "Publisher")
                        .WithMany("PublishedPostInternals")
                        .HasForeignKey("PublishedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_post_internals_publishers_published_id");

                    b.HasOne("CompanyPost.Domain.Entities.Publisher", "RecievedFrom")
                        .WithMany("RecievedPostInternals")
                        .HasForeignKey("RecievedFromId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_post_internals_publishers_recieved_from_id");

                    b.HasOne("CompanyPost.Domain.Entities.WorkType", "WorkType")
                        .WithMany("PostInternals")
                        .HasForeignKey("WorkTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_post_internals_work_types_work_type_id");

                    b.Navigation("Company");

                    b.Navigation("CreatedBy");

                    b.Navigation("Publisher");

                    b.Navigation("RecievedFrom");

                    b.Navigation("WorkType");
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.PostInternalAttachment", b =>
                {
                    b.HasOne("CompanyPost.Domain.Entities.PostInternal", "PostInternal")
                        .WithMany("Attachments")
                        .HasForeignKey("PostInternalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_post_internal_attachments_post_internals_post_internal_id");

                    b.Navigation("PostInternal");
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.PostTransformer", b =>
                {
                    b.HasOne("CompanyPost.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_transformers_companies_company_id");

                    b.HasOne("CompanyPost.Domain.Entities.SysUsers", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_transformers_sys_users_created_by_id");

                    b.HasOne("CompanyPost.Domain.Entities.Publisher", "Publisher")
                        .WithMany("PublishedPostTransformers")
                        .HasForeignKey("PublishedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_post_transformers_publishers_published_id");

                    b.HasOne("CompanyPost.Domain.Entities.Publisher", "RecievedFrom")
                        .WithMany("RecievedPostTransformers")
                        .HasForeignKey("RecievedFromId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_post_transformers_publishers_recieved_from_id");

                    b.HasOne("CompanyPost.Domain.Entities.WorkType", "WorkType")
                        .WithMany("PostTransformers")
                        .HasForeignKey("WorkTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_post_transformers_work_types_work_type_id");

                    b.Navigation("Company");

                    b.Navigation("CreatedBy");

                    b.Navigation("Publisher");

                    b.Navigation("RecievedFrom");

                    b.Navigation("WorkType");
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.PostTransformerAttachment", b =>
                {
                    b.HasOne("CompanyPost.Domain.Entities.PostTransformer", "PostTransformer")
                        .WithMany("Attachments")
                        .HasForeignKey("PostTransformerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_post_transformer_attachments_post_transformers_post_transfor");

                    b.Navigation("PostTransformer");
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.PurchaseOrder", b =>
                {
                    b.HasOne("CompanyPost.Domain.Entities.SysUsers", "CreatedBy")
                        .WithMany("PurchaseOrdersCreatedBy")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_orders_sys_users_created_by_id");

                    b.HasOne("CompanyPost.Domain.Entities.Publisher", "PersonOrgs")
                        .WithMany("PurchaseOrdersPersonOrgs")
                        .HasForeignKey("PersonOrgId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_orders_publishers_person_org_id");

                    b.HasOne("CompanyPost.Domain.Entities.Publisher", "Projects")
                        .WithMany("PurchaseOrderProjects")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_orders_publishers_project_id");

                    b.HasOne("CompanyPost.Domain.Entities.WorkType", "WorkType")
                        .WithMany("PurchaseOrdersWorkTypes")
                        .HasForeignKey("WorkTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_orders_work_types_work_type_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("PersonOrgs");

                    b.Navigation("Projects");

                    b.Navigation("WorkType");
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.PurchaseOrderAttachment", b =>
                {
                    b.HasOne("CompanyPost.Domain.Entities.PurchaseOrder", "PurchaseOrder")
                        .WithMany("PurchaseOrderAttachments")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_order_attachments_purchase_orders_purchase_order_id");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.SysUsersCompany", b =>
                {
                    b.HasOne("CompanyPost.Domain.Entities.Company", "Company")
                        .WithMany("SysUsersCompanies")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sys_users_companies_companies_company_id");

                    b.HasOne("CompanyPost.Domain.Entities.SysUsers", "SysUser")
                        .WithMany("SysUsersCompanies")
                        .HasForeignKey("SysUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sys_users_companies_sys_users_sys_user_id");

                    b.Navigation("Company");

                    b.Navigation("SysUser");
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.Company", b =>
                {
                    b.Navigation("SysUsersCompanies");
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.ContractRef", b =>
                {
                    b.Navigation("ContractAttachments");
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.Contracts", b =>
                {
                    b.Navigation("ContractAttachments");

                    b.Navigation("ContractRefs");
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.Employees", b =>
                {
                    b.Navigation("inComingResponsibleEmployees");
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.InComing", b =>
                {
                    b.Navigation("IncomingAttachments");

                    b.Navigation("inComingResponsibleEmployees");
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.PostExternal", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.PostInternal", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.PostTransformer", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.Publisher", b =>
                {
                    b.Navigation("ContractRefPersonOrgs");

                    b.Navigation("ContractRefProjects");

                    b.Navigation("ContractsPersonOrgs");

                    b.Navigation("ContractsProjects");

                    b.Navigation("IncomingProjects");

                    b.Navigation("OriginalPublisherInComings");

                    b.Navigation("PublishedInComings");

                    b.Navigation("PublishedPostExternals");

                    b.Navigation("PublishedPostInternals");

                    b.Navigation("PublishedPostTransformers");

                    b.Navigation("PurchaseOrderProjects");

                    b.Navigation("PurchaseOrdersPersonOrgs");

                    b.Navigation("RecievedPostExternals");

                    b.Navigation("RecievedPostInternals");

                    b.Navigation("RecievedPostTransformers");
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.PurchaseOrder", b =>
                {
                    b.Navigation("PurchaseOrderAttachments");
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.SysUsers", b =>
                {
                    b.Navigation("ContractRefs");

                    b.Navigation("Contracts");

                    b.Navigation("IncomingDocuments");

                    b.Navigation("PurchaseOrdersCreatedBy");

                    b.Navigation("SysUsersCompanies");
                });

            modelBuilder.Entity("CompanyPost.Domain.Entities.WorkType", b =>
                {
                    b.Navigation("ContractRefs");

                    b.Navigation("Contracts");

                    b.Navigation("InComings");

                    b.Navigation("PostExternals");

                    b.Navigation("PostInternals");

                    b.Navigation("PostTransformers");

                    b.Navigation("PurchaseOrdersWorkTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
