namespace CompanyPost.Application.DTO.Request;
public record CreatePostInternalDTO(
	int SerialNumber,
	string DocumentNumber,
	Guid CompanyId ,
	Guid PublishedId,
	Guid RecivedFromId,
	Guid WorkTypeId,
	string Subject,
	DateTime DocumentDate,
	DateTime DeliveryDate ,
	string Summary,
	string? Notes,
	int DeliveryMethod,
	int PostDocumentType,
    string? InComingNumber,
    string EmailContent,
    IEnumerable<Guid> SentEmailsTo,
    string FollowingPerson,
    List<IFormFile>? Attachments,
	int StatusMethod,
	string OldRef);