namespace CompanyPost.Application.DTO.Request;
public record CreateContractDTO(
	double Value ,
	string Details,
	string ContractNum,
	DateTime ContractDate,
	DateTime DateOfReceipt,
	DateTime ApprovalDeliveryDate,
    Guid PersonOrgId,
	Guid WorkTypeId,
	string? Notes,
	Guid ProjectId,
	int Currency,
	int? Department,
	string? PurchaseOrdNumRef ,
	ContractTypes HasReference,
	string? BaseContractId,
    string? CommercialRegisterNumber,
	string? OldRef,
    string? EmailContent,
    IEnumerable<Guid>? SentEmailsTo,
    List<IFormFile>? Attachments);
